use crate::AppState;
use eframe::egui::{self, Color32, RichText, ScrollArea, TextEdit};
use pdbg_core::{escape_pdf_text, EgressFormat, EscapedText};

const VIRTUAL_TREE_ROWS: usize = 1_000_000;
const STREAM_TOTAL_BYTES: usize = 64 * 1024 * 1024;
const HEX_WINDOW_BYTES: usize = 512;
const COPY_LIMIT_BYTES: usize = 4096;

pub fn run_gui() -> eframe::Result<()> {
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default()
            .with_title("pdbg UI Shell Spike")
            .with_inner_size([1440.0, 900.0]),
        ..Default::default()
    };

    eframe::run_native(
        "pdbg UI Shell Spike",
        options,
        Box::new(|_cc| Ok(Box::new(GuiShellApp::new()))),
    )
}

pub struct GuiShellApp {
    state: Result<AppState, String>,
    tree: VirtualObjectTree,
    stream: LargeStreamModel,
    selected_row: usize,
    back_stack: Vec<usize>,
    forward_stack: Vec<usize>,
    selected_tab: InspectorTab,
    copied_excerpt: Option<EscapedText>,
    status_log: Vec<String>,
}

impl GuiShellApp {
    pub fn new() -> Self {
        let state = AppState::new_headless().map_err(|err| err.message);
        Self {
            state,
            tree: VirtualObjectTree::new(VIRTUAL_TREE_ROWS),
            stream: LargeStreamModel::default(),
            selected_row: 0,
            back_stack: Vec::new(),
            forward_stack: Vec::new(),
            selected_tab: InspectorTab::Object,
            copied_excerpt: None,
            status_log: vec![
                "fake shim opened fake.pdf".to_string(),
                "virtual object tree uses generated rows".to_string(),
                "large stream pane uses generated bytes".to_string(),
            ],
        }
    }

    fn summary_line(&self) -> String {
        match &self.state {
            Ok(state) => state
                .panels
                .summary
                .as_ref()
                .map(|summary| {
                    format!(
                        "{} | pages {} | xref {} | safe mode {}",
                        summary.file_path,
                        summary.page_count,
                        summary.xref_size,
                        summary.safety.safe_mode
                    )
                })
                .unwrap_or_else(|| "summary unavailable".to_string()),
            Err(err) => format!("failed to initialize fake shim: {err}"),
        }
    }

    fn selected_object_label(&self) -> String {
        self.tree.row_label(self.selected_row)
    }

    fn select_row_from_tree(&mut self, row: usize) {
        if self.selected_row == row {
            return;
        }
        self.selected_row = row;
        self.forward_stack.clear();
        self.status_log
            .push(format!("selected {}", self.tree.row_label(row)));
    }

    fn follow_reference(&mut self, row: usize) {
        if self.selected_row == row || row >= self.tree.row_count() {
            return;
        }
        self.back_stack.push(self.selected_row);
        self.forward_stack.clear();
        self.selected_row = row;
        self.selected_tab = InspectorTab::Object;
        self.status_log.push(format!(
            "resolved reference to {}",
            self.tree.row_label(row)
        ));
    }

    fn go_back(&mut self) {
        if let Some(row) = self.back_stack.pop() {
            self.forward_stack.push(self.selected_row);
            self.selected_row = row;
            self.status_log
                .push(format!("back to {}", self.tree.row_label(row)));
        }
    }

    fn go_forward(&mut self) {
        if let Some(row) = self.forward_stack.pop() {
            self.back_stack.push(self.selected_row);
            self.selected_row = row;
            self.status_log
                .push(format!("forward to {}", self.tree.row_label(row)));
        }
    }
}

impl eframe::App for GuiShellApp {
    fn ui(&mut self, ui: &mut egui::Ui, _frame: &mut eframe::Frame) {
        let ctx = ui.ctx().clone();

        egui::Panel::top("top_bar").show_inside(ui, |ui| {
            ui.horizontal_wrapped(|ui| {
                ui.label(RichText::new("pdbg").strong());
                if ui
                    .add_enabled(!self.back_stack.is_empty(), egui::Button::new("Back"))
                    .clicked()
                {
                    self.go_back();
                }
                if ui
                    .add_enabled(!self.forward_stack.is_empty(), egui::Button::new("Forward"))
                    .clicked()
                {
                    self.go_forward();
                }
                ui.separator();
                ui.label(self.summary_line());
                ui.separator();
                ui.label(format!("scale {:.2}x", ctx.pixels_per_point()));
            });
        });

        egui::Panel::bottom("log_panel")
            .resizable(true)
            .default_size(150.0)
            .show_inside(ui, |ui| self.draw_log(ui));

        egui::Panel::left("document_tree")
            .resizable(true)
            .default_size(320.0)
            .size_range(220.0..=520.0)
            .show_inside(ui, |ui| self.draw_tree(ui));

        egui::Panel::right("inspector")
            .resizable(true)
            .default_size(440.0)
            .size_range(320.0..=680.0)
            .show_inside(ui, |ui| self.draw_inspector(ui, &ctx));

        egui::CentralPanel::default().show_inside(ui, |ui| self.draw_page_preview(ui));
    }
}

impl GuiShellApp {
    fn draw_tree(&mut self, ui: &mut egui::Ui) {
        ui.heading("Document Tree");
        ui.horizontal(|ui| {
            ui.label("Rows");
            ui.monospace(self.tree.row_count().to_string());
        });

        let row_height = ui.text_style_height(&egui::TextStyle::Body) + 6.0;
        ScrollArea::vertical().show_rows(ui, row_height, self.tree.row_count(), |ui, range| {
            for row in range {
                let label = self.tree.row_label(row);
                let selected = row == self.selected_row;
                if ui.selectable_label(selected, label).clicked() {
                    self.select_row_from_tree(row);
                }
            }
        });
    }

    fn draw_page_preview(&mut self, ui: &mut egui::Ui) {
        ui.heading("Page Preview");
        ui.label("Fake page renderer surface");

        let available = ui.available_size();
        let desired = egui::vec2(available.x.max(320.0), available.y.max(360.0));
        let (rect, _) = ui.allocate_exact_size(desired, egui::Sense::hover());
        let painter = ui.painter_at(rect);
        painter.rect_filled(rect, 0.0, Color32::from_rgb(42, 45, 48));

        let margin = 28.0;
        let page_rect = egui::Rect::from_min_max(
            rect.min + egui::vec2(margin, margin),
            rect.max - egui::vec2(margin, margin),
        );
        painter.rect_filled(page_rect, 2.0, Color32::from_rgb(246, 245, 240));
        painter.rect_stroke(
            page_rect,
            2.0,
            egui::Stroke::new(1.0, Color32::from_rgb(155, 155, 150)),
            egui::StrokeKind::Outside,
        );

        let content = page_rect.shrink(34.0);
        for index in 0..9 {
            let y = content.top() + index as f32 * 26.0;
            painter.line_segment(
                [
                    egui::pos2(content.left(), y),
                    egui::pos2(content.right() - (index % 3) as f32 * 54.0, y),
                ],
                egui::Stroke::new(3.0, Color32::from_rgb(80, 88, 95)),
            );
        }

        let highlight = egui::Rect::from_min_size(
            egui::pos2(content.left() + 36.0, content.top() + 190.0),
            egui::vec2(220.0, 86.0),
        );
        painter.rect_stroke(
            highlight,
            1.0,
            egui::Stroke::new(2.0, Color32::from_rgb(210, 96, 54)),
            egui::StrokeKind::Outside,
        );
        painter.text(
            highlight.left_top() + egui::vec2(8.0, 8.0),
            egui::Align2::LEFT_TOP,
            self.selected_object_label(),
            egui::FontId::monospace(13.0),
            Color32::from_rgb(80, 44, 32),
        );
    }

    fn draw_inspector(&mut self, ui: &mut egui::Ui, ctx: &egui::Context) {
        ui.heading("Inspector");
        ui.horizontal(|ui| {
            self.tab_button(ui, InspectorTab::Object, "Object");
            self.tab_button(ui, InspectorTab::Stream, "Stream");
            self.tab_button(ui, InspectorTab::Diagnostics, "Diagnostics");
        });
        ui.separator();

        match self.selected_tab {
            InspectorTab::Object => self.draw_object_panel(ui),
            InspectorTab::Stream => self.draw_stream_panel(ui, ctx),
            InspectorTab::Diagnostics => self.draw_diagnostics_panel(ui),
        }
    }

    fn tab_button(&mut self, ui: &mut egui::Ui, tab: InspectorTab, label: &str) {
        if ui
            .selectable_label(self.selected_tab == tab, label)
            .on_hover_text(format!("{label} panel"))
            .clicked()
        {
            self.selected_tab = tab;
        }
    }

    fn draw_object_panel(&mut self, ui: &mut egui::Ui) {
        ui.label(RichText::new(self.selected_object_label()).monospace());
        ui.separator();
        ui.label("Indirect references");
        ui.horizontal_wrapped(|ui| {
            for target in self.tree.reference_targets(self.selected_row) {
                if ui
                    .link(format!("{target} 0 R"))
                    .on_hover_text("Resolve reference and push navigation history")
                    .clicked()
                {
                    self.follow_reference(target);
                }
            }
        });
        ui.separator();
        if let Ok(state) = &self.state {
            if let Some(preview) = &state.panels.detail_preview {
                ui.label("Preview");
                ui.monospace(preview);
            }
            if let Some(summary) = &state.panels.summary {
                ui.separator();
                ui.label("Document summary");
                ui.monospace(format!("hash: {:?}", summary.file_hash));
                ui.monospace(format!("version: {:?}", summary.pdf_version));
                ui.monospace(format!(
                    "permissions: print={} copy={} modify={}",
                    summary.permissions.print, summary.permissions.copy, summary.permissions.modify
                ));
            }
        } else if let Err(err) = &self.state {
            ui.colored_label(Color32::from_rgb(190, 62, 62), err);
        }
    }

    fn draw_stream_panel(&mut self, ui: &mut egui::Ui, ctx: &egui::Context) {
        ui.horizontal(|ui| {
            ui.label("Offset");
            ui.add(
                egui::DragValue::new(&mut self.stream.offset)
                    .range(0..=STREAM_TOTAL_BYTES.saturating_sub(HEX_WINDOW_BYTES))
                    .speed(64),
            );
        });
        ui.horizontal(|ui| {
            ui.label("Selection");
            ui.add(
                egui::DragValue::new(&mut self.stream.selection_offset)
                    .range(0..=STREAM_TOTAL_BYTES.saturating_sub(1))
                    .speed(64),
            );
            ui.add(
                egui::DragValue::new(&mut self.stream.selection_len)
                    .range(1..=32 * 1024)
                    .speed(16),
            );
        });

        let mut hex = self.stream.hex_window();
        ui.add(
            TextEdit::multiline(&mut hex)
                .font(egui::TextStyle::Monospace)
                .desired_rows(18)
                .code_editor(),
        );

        if ui.button("Copy escaped excerpt").clicked() {
            let escaped = self.stream.escaped_selection();
            ctx.copy_text(escaped.text.clone());
            self.status_log.push(format!(
                "copied bounded excerpt{}",
                if escaped.truncated {
                    " (truncated)"
                } else {
                    ""
                }
            ));
            self.copied_excerpt = Some(escaped);
        }

        if let Some(escaped) = &self.copied_excerpt {
            ui.separator();
            ui.label(if escaped.truncated {
                "Last copied excerpt (truncated)"
            } else {
                "Last copied excerpt"
            });
            let mut copied = escaped.text.clone();
            ui.add(
                TextEdit::multiline(&mut copied)
                    .font(egui::TextStyle::Monospace)
                    .desired_rows(5)
                    .interactive(false),
            );
        }
    }

    fn draw_diagnostics_panel(&mut self, ui: &mut egui::Ui) {
        if let Ok(state) = &self.state {
            let diagnostics = state
                .panels
                .summary
                .as_ref()
                .map(|summary| summary.diagnostics.as_slice())
                .unwrap_or(&[]);
            if diagnostics.is_empty() {
                ui.label("No fake diagnostics");
            } else {
                for diagnostic in diagnostics {
                    ui.monospace(format!(
                        "{} {} {}",
                        diagnostic.severity.as_public_str(),
                        diagnostic.code.as_public_str(),
                        diagnostic.message
                    ));
                }
            }
        }
    }

    fn draw_log(&mut self, ui: &mut egui::Ui) {
        ui.horizontal(|ui| {
            ui.heading("Log");
            if ui.button("Clear").clicked() {
                self.status_log.clear();
            }
        });
        ScrollArea::vertical().stick_to_bottom(true).show(ui, |ui| {
            for line in &self.status_log {
                ui.monospace(line);
            }
        });
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum InspectorTab {
    Object,
    Stream,
    Diagnostics,
}

#[derive(Clone, Debug)]
pub(crate) struct VirtualObjectTree {
    rows: usize,
}

impl VirtualObjectTree {
    pub(crate) fn new(rows: usize) -> Self {
        Self { rows }
    }

    pub(crate) fn row_count(&self) -> usize {
        self.rows + 1
    }

    pub(crate) fn row_label(&self, row: usize) -> String {
        if row == 0 {
            return "root / catalog".to_string();
        }
        format!(
            "obj {:06} 0 R  /FakeNode{}",
            row,
            row.wrapping_mul(31) % 997
        )
    }

    pub(crate) fn reference_targets(&self, row: usize) -> [usize; 3] {
        let base = row.max(1);
        [
            (base * 3 % self.rows).max(1),
            (base * 11 % self.rows).max(1),
            (base * 101 % self.rows).max(1),
        ]
    }
}

#[derive(Clone, Debug)]
pub(crate) struct LargeStreamModel {
    offset: usize,
    selection_offset: usize,
    selection_len: usize,
}

impl Default for LargeStreamModel {
    fn default() -> Self {
        Self {
            offset: 0,
            selection_offset: 0,
            selection_len: 256,
        }
    }
}

impl LargeStreamModel {
    pub(crate) fn hex_window(&self) -> String {
        self.hex_dump(self.offset, HEX_WINDOW_BYTES)
    }

    pub(crate) fn escaped_selection(&self) -> EscapedText {
        let text = self.hex_dump(
            self.selection_offset,
            self.selection_len.min(COPY_LIMIT_BYTES),
        );
        let max_bytes = COPY_LIMIT_BYTES.min(text.len());
        let mut escaped = escape_pdf_text(&text, EgressFormat::Markdown, max_bytes);
        escaped.truncated |= self.selection_len > COPY_LIMIT_BYTES;
        escaped
    }

    fn hex_dump(&self, offset: usize, len: usize) -> String {
        let start = offset.min(STREAM_TOTAL_BYTES);
        let end = start.saturating_add(len).min(STREAM_TOTAL_BYTES);
        let mut out = String::new();
        let mut line = start;
        while line < end {
            let line_end = (line + 16).min(end);
            out.push_str(&format!("{line:08x}  "));
            for index in line..line_end {
                out.push_str(&format!("{:02x} ", fake_stream_byte(index)));
            }
            for _ in line_end..line + 16 {
                out.push_str("   ");
            }
            out.push(' ');
            for index in line..line_end {
                let byte = fake_stream_byte(index);
                out.push(if byte.is_ascii_graphic() {
                    byte as char
                } else {
                    '.'
                });
            }
            out.push('\n');
            line = line_end;
        }
        out
    }
}

fn fake_stream_byte(index: usize) -> u8 {
    (index as u8).wrapping_mul(31).wrapping_add(17)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn virtual_tree_does_not_materialize_rows() {
        let tree = VirtualObjectTree::new(1_000_000);
        assert_eq!(tree.row_count(), 1_000_001);
        assert_eq!(tree.row_label(0), "root / catalog");
        assert_eq!(tree.row_label(999_999), "obj 999999 0 R  /FakeNode248");
    }

    #[test]
    fn stream_excerpt_is_bounded_and_escaped() {
        let model = LargeStreamModel {
            offset: 0,
            selection_offset: 0,
            selection_len: 16 * 1024,
        };
        let escaped = model.escaped_selection();
        assert!(escaped.truncated);
        assert!(escaped.text.len() < COPY_LIMIT_BYTES * 2);
        assert!(escaped.text.contains("00000000"));
    }

    #[test]
    fn stream_hex_window_uses_generated_bytes() {
        let model = LargeStreamModel::default();
        let window = model.hex_window();
        assert!(window.starts_with("00000000  11 30 4f 6e"));
        assert!(window.lines().count() > 1);
    }

    #[test]
    fn reference_navigation_uses_back_forward_history() {
        let mut app = GuiShellApp::new();
        assert_eq!(app.selected_row, 0);

        app.follow_reference(42);
        assert_eq!(app.selected_row, 42);
        assert_eq!(app.back_stack, vec![0]);
        assert!(app.forward_stack.is_empty());

        app.go_back();
        assert_eq!(app.selected_row, 0);
        assert_eq!(app.forward_stack, vec![42]);
    }
}
